name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort mypy

    - name: Check formatting with black
      run: black --check --diff nextjs_hydration_parser/ tests/ examples/

    - name: Check import sorting with isort
      run: isort --check-only --diff nextjs_hydration_parser/ tests/ examples/

    - name: Type check with mypy (optional, non-blocking)
      run: |
        mypy nextjs_hydration_parser --ignore-missing-imports || true

  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        pytest tests/ --cov=nextjs_hydration_parser --cov-report=html --cov-report=term --cov-fail-under=80

    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-report
        path: htmlcov/

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety pip-audit

    - name: Run bandit security check
      run: |
        bandit -r nextjs_hydration_parser/ -ll

    - name: Run safety check
      run: |
        safety check

    - name: Run pip-audit
      run: |
        pip-audit
